repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # Prettier hook optional; enable when a stable tag is selected
  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: v4.0.0
  #   hooks:
  #     - id: prettier
  #       files: ^apps/desktop/
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        language: system
        entry: bash -lc 'cargo fmt --all -- --check'
        pass_filenames: false
  - repo: local
    hooks:
      - id: cargo-clippy
        name: cargo clippy
        language: system
        entry: bash -lc 'cargo clippy --all-targets -- -D warnings'
        pass_filenames: false
