[package]
name = "desktop"
version = "0.1.0"
authors = ["You"]
edition = "2021"

[dependencies]
tauri = { version = "1.6.1", features = ["shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
tauri-build = { version = "1.5.2", features = [] }
