[package]
name = "solver"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true

[dev-dependencies]
approx.workspace = true
